version: '3'
services:
  # PHP Service
  austand_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: austand-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - quran-network

  # Queue Runner Service
  queue_runner:
    image: php:8.3-fpm
    container_name: queue-runner
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    command: php artisan queue:work
    networks:
      - quran-network

  # Nginx Service
  auwebserver:
    image: nginx:1.27.0
    container_name: auwebserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - quran-network
    ports:
      - "8080:80"

# Docker Networks
networks:
  quran-network:
    driver: bridge


